```{r}
source("main.R")
library(ggplot2)
```

```{r}
ratings.unnorm <- load_ratings()
ratings <- normalize_ratings(ratings.unnorm)
```

```{r}
boxplot(ratings[c("interest", "comprehension", "complexity")])
boxplot(ratings.unnorm[c("interest", "comprehension", "complexity")])
```

```{r}

ggplot(data=ratings, aes(x = comprehension, y = complexity, color = interest)) + geom_point()


ggplot(data=ratings.unnorm, aes(x = comprehension, y = complexity, color = interest)) + geom_point()
```


Look at correlation between familiarity, complexity, and comprehension to interest.
```{r}
cor(ratings[, c("complexity", "comprehension", "interest")])
```

See if we can produce a linear model between these variables
```{r}
linearMod <- lm(interest ~ complexity + comprehension, data = ratings)
summary(linearMod)
grid <- data.frame(expand.grid(complexity=seq(1,7, length.out=20), comprehension=seq(1,7, length.out=20)))
grid$interest <- predict(linearMod, grid)

ggplot(grid) + geom_point(aes(x = comprehension, y = complexity, color = interest))
```

