---
title: "rawfile-exploration"
output: html_document
---
```{r}
library(ggplot2)
library(stringr)
```

```{r}
load_files <- function(n = NULL, pattern = NULL) {
  files <- dir("data/raw", pattern)
  
  if(is.numeric(n)) {
    files <- files[1:n]
  }
  
  files <- lapply(files, function(name) {
    df <- read.csv(paste("data/raw", name, sep = "/"))
    # extract subjectid and textid from filename
    p <- str_match(name, "P([0-9]*)_([0-9]*)")
    pid <- p[[2]]
    tid <- p[[3]]
    
    df2 <- data.frame(
      time = df$Time,
      x = df$L.POR.X..px.,
      y = df$L.POR.Y..px.,
      pid = replicate(nrow(df), pid),
      tid = replicate(nrow(df), tid)
    )
    return(df2)
  })
  return(files)
  
}
files <- load_files(pattern="P.*_10879")

```


```{r}
remove_outliers <- function(dflist) {
  filtered <- list()
  for(i in 1:length(dflist)) {
    file <- dflist[[i]]
    original.length <- nrow(file)
    filt <- file$x > 1 & file$y > 1
    file <- file[filt,]
    
    
    outlier_filter <- rep(TRUE, nrow(file))

    g <- ggplot()
    window <- 800
    step <- 800
    j <- 1
    k <- window
    while(k <= nrow(file)) {
      segment <- file[j:k, ]
      t <- boxplot.stats(segment$y)$stats
      
      below <- segment$y < t[1]
      above <- segment$y > t[5]
      outlier_filter[j:k] <- outlier_filter[j:k] & (above | below)
      
      if (k == nrow(file)) {
        break
      }
      j <- j + step
      k <- min(nrow(file), k + step)
    }
    
    outliers <- file[outlier_filter,]
    g <- g + geom_point(data = outliers, aes(x = time, y = y))
    g <- g + geom_path(data = file, aes(x = time, y = y))
    
    print(g)
    
    
    file <- file[!outlier_filter, ]
    print(ggplot(data = file, aes(x = time, y = y)) + geom_path())
    
    # dont keep files that has a majority of outliers
    if ((nrow(file) / original.length) > .9) {
      filtered[[length(filtered) + 1]] <- file
    }
  }
  
  return(filtered)
}

files.no <- remove_outliers(files)
```


```{r}
interpolate_files <- function(dflist) {
  interpolated <- list()
  for(i in 1:length(dflist)) {
    file <- dflist[[i]]
    deltas <- filter(file$time, filter=c(1,-1), sides=1)
    # first delta is always null
    deltas <- deltas[2:length(deltas)]
    # approximate period
    period <- median(deltas)
  
    interpolations <- data.frame()
    for(i in 1:(nrow(file)-1)) {
      d <- file[i+1,]$time - file[i,]$time
      
      # interpolate values if number of missing samples
      # is less than 75ms (less than a blink)
      # and more than 32ms (at least one sample missing).
      if (d > 32000 && d < 75000) {
        samples.missing <- round(d/period) - 1
        df <- file[i:(i+1),]
        j <- data.frame(lapply(df[,c('time', 'x', 'y')], function(column) {
          inter <- approx(df$time, column, n = samples.missing + 2)$y
          return(inter[1:samples.missing+1])
        }))
        j$pid <- rep(file$pid[1], samples.missing)
        j$tid <- rep(file$tid[1], samples.missing)
        interpolations <- rbind(interpolations, j)
      }
    }
    df <- rbind(file, interpolations)
    df <- df[order(df$time), ]
    
    interpolated[[length(interpolated) + 1]] <- df
  }
  return(interpolated)
}

files.interpolated <- interpolate_files(files.no)
```


```{r}
smooth_files <- function(dflist, n = 5) {
  smoothed <- list()
  for(i in 1:length(dflist)) {
    file <- dflist[[i]]
    file$y <- filter(file$y, filter = rep(1/n, n), sides=1)
    file$x <- filter(file$x, filter = rep(1/n, n), sides=1)
    smoothed[[length(smoothed) + 1]] <- file[n:nrow(file),]
  }
  
  return(smoothed)
}

files.smoothed <- smooth_files(files.interpolated)
```



```{r}
for(i in 1:length(files.smoothed)) {
  g <- ggplot(files.smoothed[[i]], aes(x=time, y = y, color = time)) + geom_path()
  print(g)
}
```

```{r}
library(emov)
```

```{r}
to_fixations <- function(dflist) {
  fixations <- list()
  for(i in 1:length(dflist)) {
    file <- dflist[[i]]
    fixations[[i]] <- emov.idt(file$time, file$x, file$y, 75, 8)
  }
  return(fixations)
}

files.fixations <- to_fixations(files.smoothed)
```


```{r}
for(i in 1:length(files.fixations)) {
  g <- ggplot(files.fixations[[i]], aes(x = x, y = y)) + 
    geom_path(color = 'darkred') +
    geom_point(size = 2)
  print(g)
}
```

